[versions]

decompose = "1.0.0-beta-01-native-compose"
kotlin = "1.7.20"
essenty = "0.7.0"
parcelizeDarwin = "0.1.2"
reaktive = "1.2.1"
junit = "4.13.2"
jetbrainsCompose = "1.2.0"
jetbrainsKotlinWrappers = "0.0.1-pre.325-kotlin-1.6.10"
jetbrainsKotlinxCoroutines = "1.6.1"
jetbrainsBinaryCompatibilityValidator = "0.10.0"
jetpackCompose = "1.2.1"
jetpackComposeCompiler = "1.3.2"
androidGradle = "7.2.2"
androidMaterial = "1.3.0"
androidPlay = "1.10.0"
androidxCore = "1.3.2"
androidxAppcompat = "1.2.0"
androidxLifecycle = "2.3.1"
androidxActivity = "1.3.1"
androidxTestCore = "1.4.0"

[libraries]

kotlin-kotlinGradlePlug = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

essenty-lifecycle = { group = "com.arkivanov.essenty", name = "lifecycle", version.ref = "essenty" }
essenty-stateKeeper = { group = "com.arkivanov.essenty", name = "state-keeper", version.ref = "essenty" }
essenty-instanceKeeper = { group = "com.arkivanov.essenty", name = "instance-keeper", version.ref = "essenty" }
essenty-backHandler = { group = "com.arkivanov.essenty", name = "back-handler", version.ref = "essenty" }

parcelizeDarwin-gradlePlug = { group = "com.arkivanov.parcelize.darwin", name = "gradle-plugin", version.ref = "parcelizeDarwin" }
parcelizeDarwin-runtime = { group = "com.arkivanov.parcelize.darwin", name = "runtime", version.ref = "parcelizeDarwin" }

reaktive-reaktive = { group = "com.badoo.reaktive", name = "reaktive", version.ref = "reaktive" }
reaktive-coroutinesInterop = { group = "com.badoo.reaktive", name = "coroutines-interop", version.ref = "reaktive" }

junit-junit = { group = "junit", name = "junit", version.ref = "junit" }

jetbrains-compose-composeGradlePlug = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "jetbrainsCompose" }
jetbrains-compose-ui-uiTestJunit4 = { group = "org.jetbrains.compose.ui", name = "ui-test-junit4", version.ref = "jetbrainsCompose" }
jetbrains-kotlinWrappers-kotlinWrappersBom = { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-wrappers-bom", version.ref = "jetbrainsKotlinWrappers" }
jetbrains-kotlinx-binaryCompatibilityValidator = { group = "org.jetbrains.kotlinx", name = "binary-compatibility-validator", version.ref = "jetbrainsBinaryCompatibilityValidator" }
jetbrains-kotlinx-kotlinxCoroutinesSwing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "jetbrainsKotlinxCoroutines" }

androidx-compose-runtime-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "jetpackCompose" }

android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradle" }
android-material-material = { group = "com.google.android.material", name = "material", version.ref = "androidMaterial" }
android-play-core = { group = "com.google.android.play", name = "core", version.ref = "androidPlay" }

androidx-core-coreKtx  = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat-appcompat  = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-lifecycle-lifecycleCommonJava8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "androidxLifecycle" }
androidx-activity-activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-activity-activityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
